# Internal CLI Package Manifest
# Must synchronize with PKGBUILD declarations in caelestia-meta

packages = [
    "caelestia-cli",
    "caelestia-shell",
    "hyprland",
    "xdg-desktop-portal-hyprland",
    "xdg-desktop-portal-gtk",
    "hyprpicker",
    "gnome-keyring",
    "polkit-gnome",
    "wl-clipboard",
    "cliphist",
    "grim",
    "slurp",
    "swappy",
    "fuzzel",
    "brightnessctl",
    "ddcutil",
    "networkmanager",
    "libnotify",
    "playerctl",
    "gpu-screen-recorder",
    "dart-sass",
    "inotify-tools",
    "app2unit",
    "wireplumber",
    "trash-cli",
    "foot",
    "fish",
    "eza",
    "fastfetch",
    "starship",
    "btop",
    "jq",
    "adw-gtk-theme",
    "papirus-icon-theme",
    "qtengine",
    "ttf-jetbrains-mono-nerd",
]
